# -*- coding: utf-8 -*-
# Copyright (c) CloudZero, Inc. All rights reserved.
# Licensed under the MIT License. See LICENSE file in the project root for full license information.

service: dyn-o-tool
frameworkVersion: ">=1.0.0 <2.0.0"

plugins:
  - serverless-cf-vars

provider:
  name: aws
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${opt:aws-profile, env:AWS_PROFILE, env:AWS_DEFAULT_PROFILE, self:custom.defaultProfile}
  stackTags:
    cloudzero:service: ${self:service}
  versionFunctions: false
  runtime: python3.6
  timeout: 300
  environment:
    PYTHONPATH: "/var/runtime:/var/task/vendored"
    NAMESPACE: ${self:provider.stage}
    LOG_LEVEL: INFO
  iamRoleStatements:
  - Effect: Allow
    Action: # Give permission to CZ Reactor DynamoDB tables
      - "dynamodb:*"
    Resource: "arn:aws:dynamodb:*:*:table/cz*"
  - Effect: Allow
    Action:
      - "lambda:*"
    Resource: "*"
  - Effect: "Allow"
    Action:
      - "s3:*"
    Resource: "*"

custom:
  defaultStage: dev
  defaultProfile: default
  prune:
    automatic: true
    number: 3

functions:
  dump-table:
    handler: functions.dump_table
  dump-table-launcher:
    handler: functions.dump_table_launcher

resources:
  Resources:
    lambdakey:
      Type: AWS::KMS::Key
      Properties:
        Description: "Sample Key for lambda"
        Enabled: true
        KeyPolicy:
          Version: "2012-10-17"
          Id: "key-lambda-1"
          Statement:
            Sid: "Allow administration of the key"
            Effect: "Allow"
            Principal:
              AWS:
                - Fn::GetAtt:
                  - IamRoleLambdaExecution
                  - Arn
                - 'arn:aws:sts::#{AWS::AccountId}:root'
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
            Resource: "*"
    lambdakeyalias:
      Type: "AWS::KMS::Alias"
      Properties:
        AliasName: "alias/SampleKey"
        TargetKeyId:
          "Fn::GetAtt":
          - lambdakey
          - Arn
    DumpDashtableLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "5"
    DumpDashtableDashlauncherLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "5"
